/*Return the shortest Name */
SELECT CITY, LENGTH(CITY) 
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;

/*Return the longest Name*/
SELECT CITY, LENGTH(CITY) 
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1;
